apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-external
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: ExternalName
  externalName: {{ .Values.elasticsearch.host }}
  ports:
    - port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
      protocol: TCP
