apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-lb
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app.name }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.app.loadbalancer.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
