{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  labels:
    app: {{ .Values.redis.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.redis.name }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.redis.service.port }}
      name: redis
{{- end }}
