apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  # PostgreSQL password
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}

  # AWS Credentials
  AWS_ACCESS_KEY: {{ .Values.aws.accessKey | quote }}
  AWS_SECRET_KEY: {{ .Values.aws.secretKey | quote }}

  # JWT Secret
  JWT_SECRET_KEY: {{ .Values.jwt.secretKey | quote }}
